"""
portfolio_analytics.py

Analyze the optimized portfolio generated by the
classical optimizer.

This module calculates portfolio performance metrics
and validates investment constraints.
"""

from pathlib import Path

import numpy as np
import pandas as pd

from config import (
    OUTPUT_PORTFOLIO,
    TOTAL_WEIGHT,
    MAX_WEIGHT,
)


# Configuration


RISK_FREE_RATE = 0.03



# Load Portfolio

def load_portfolio():
    """Load optimized portfolio."""

    portfolio = pd.read_csv(OUTPUT_PORTFOLIO)

    return portfolio



# Portfolio Metrics


def portfolio_return(portfolio):
    """Expected portfolio return."""

    return np.sum(
        portfolio["Expected_Return"] * portfolio["Weight"]
    )


def portfolio_risk(portfolio):
    """Approximate portfolio risk."""

    return np.sqrt(
        np.sum(
            (portfolio["Volatility"] ** 2)
            * (portfolio["Weight"] ** 2)
        )
    )


def portfolio_variance(risk):
    """Portfolio variance."""

    return risk ** 2


def sharpe_ratio(expected_return, risk):
    """Calculate Sharpe Ratio."""

    if risk == 0:
        return 0

    return (expected_return - RISK_FREE_RATE) / risk
# Allocation Summary


def asset_class_allocation(portfolio):
    """Allocation by asset class."""

    return (
        portfolio
        .groupby("Asset_Class")["Weight"]
        .sum()
        .sort_values(ascending=False)
    )



# Constraint Validation

def validate_constraints(portfolio):

    total_weight = portfolio["Weight"].sum()

    max_asset = portfolio["Weight"].max()

    print("\nConstraint Validation")
    print("-" * 30)

    print(
        f"Total Weight          : {total_weight:.15f}"
    )

    print(
        f"Maximum Asset Weight  : {max_asset:.15f}"
    )

    print(
    f"Total Weight Valid    : "
    f"{np.isclose(total_weight, TOTAL_WEIGHT, atol=1e-6)}"
)

    print(
        f"Max Weight Valid      : {max_asset <= MAX_WEIGHT + 1e-6}"
    )



# Main


def main():

    portfolio = load_portfolio()

    expected_return = portfolio_return(portfolio)

    risk = portfolio_risk(portfolio)

    variance = portfolio_variance(risk)

    sharpe = sharpe_ratio(
        expected_return,
        risk
    )

    print("=" * 50)
    print("Portfolio Analytics")
    print("=" * 50)

    print(
        f"Expected Return     : {expected_return:.4f}"
    )

    print(
        f"Portfolio Risk      : {risk:.4f}"
    )

    print(
        f"Portfolio Variance  : {variance:.6f}"
    )

    print(
        f"Sharpe Ratio        : {sharpe:.4f}"
    )

    print(
        f"Selected Assets     : {len(portfolio)}"
    )

    print("\nAsset Class Allocation")
    print("-" * 30)

    print(asset_class_allocation(portfolio))

    validate_constraints(portfolio)


if __name__ == "__main__":
    main()